# Generated by Django 5.1.3 on 2024-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMS', '0002_student_leaves_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='pendingfees',
            field=models.IntegerField(default=0),
        ),
    ]
